# Generated by Django 5.0.1 on 2024-03-28 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_alter_itinerary_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.CharField(default='742 Evergreen TerraceSpringfield, SP, 49007', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='editSummary',
            field=models.CharField(default='fake editing summary', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='lat',
            field=models.CharField(default=233434, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='lng',
            field=models.CharField(default=213412, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default=12344, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='northeast',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='openHour',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='periods',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='placeID',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='southwest',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='urlLink',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='website',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
