# Generated by Django 5.0.1 on 2024-04-02 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_activity_address_activity_editsummary_activity_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travelers', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='day',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='days',
        ),
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itineraries.day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='day_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='itinerary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(default='Eagan, MN', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='num_travelers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='title',
            field=models.CharField(default='My Vacation', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ActivityAssignment',
        ),
        migrations.DeleteModel(
            name='Traveler',
        ),
    ]
