# Generated by Django 5.0.1 on 2024-03-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_activity_address_activity_editsummary_activity_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='editSummary',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='northeast',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='openHour',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='periods',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='placeID',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='southwest',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='title',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='urlLink',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='website',
        ),
    ]
