# Generated by Django 5.0.1 on 2024-03-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_activity_address_activity_editsummary_activity_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travelers', models.IntegerField()),
            ],
        ),
    ]
