# Generated by Django 5.0.1 on 2024-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_preferencesformresponse_remove_day_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lng',
        ),
        migrations.AddField(
            model_name='activity',
            name='businessStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='photos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
