# Generated by Django 5.0.1 on 2024-03-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_activity_editsummary_activity_lat_activity_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='businessStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='photos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='activity',
            name='northeast',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='periods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='placeID',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='southwest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='urlLink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
