# Generated by Django 5.0.1 on 2024-05-03 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_remove_activity_lat_remove_activity_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='destination_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination_lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='day',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itineraries.itinerary'),
        ),
    ]
