# Generated by Django 5.0.1 on 2024-03-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_activity_businessstatus_activity_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lng',
        ),
    ]
