# Generated by Django 5.0.1 on 2024-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_remove_activity_lat_remove_activity_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='placeID',
            field=models.CharField(max_length=255),
        ),
    ]
